# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxsim {f} {f} && open {f}')
    ```
"""

from .block import (
    C1,
    C2,
    C3,
    C3TR,
    DFL,
    SPP,
    SPPF,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    ImagePoolingAttn,
    C3Ghost,
    C3x,
    GhostBottleneck,
    HGBlock,
    HGStem,
    Proto,
    RepC3,
    ResNetLayer,
    ContrastiveHead,
    BNContrastiveHead,
    RepNCSPELAN4,
    ADown,
    SPPELAN,
    CBFuse,
    CBLinear,
    Silence,
    SPPFS,
    CBC2f,
    SRFD,
    DRFD,
    SRCNN2,
    FSRCNN,
    ESPCN,
    CARAFE,
    DW_CARAFE,
    MAU,
    LiteCARAFE,
    DS_DGC,
    MAD,
    TRD,
    RFEM,
    C2EMA,
    MSCAAttention,
    C2f_RFEA,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, Detect_AFPN_P2345
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .afpn import AFPN_P2345
from .extralmodel import PFM, SED, SEG, DE, ASFD, CoordinateAttention, EMA, FCDN_MultiAttention, ACFM, LSKA, SPPF_LSKA, SE_Block, ECA, deformable_LKA_Attention, DeformConv
from .RFA import RFCBAMConv, RFCAConv, RFAConv_Unfold, RFAConv_Group

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "Silence",
    "SPPFS",
    "CBC2f",
    "SRFD",
    "SRCNN2",
    "FSRCNN",
    "ESPCN",
    "CARAFE",
    "DW_CARAFE",
    "MAU",
    "AFPN_P2345",
    "Detect_AFPN_P2345",
    "LiteCARAFE",
    "DS_DGC",
    "MAD",
    "TRD",
    "RFEM",
    "PFM",
    "DRFD",
    "SEG",
    "SED",
    "DE",
    "ASFD",
    "CoordinateAttention",
    "EMA",
    "FCDN_MultiAttention",
    "ACFM",
    "C2EMA",
    "LSKA",
    "SPPF_LSKA",
    "SE_Block",
    "MSCAAttention",
    "ECA",
    "RFCBAMConv",
    "RFCAConv",
    "RFAConv_Unfold",
    "RFAConv_Group",
    "C2f_RFEA",
)
